version: '2'

services:
  postgres:
    image: postgres:latest
    container_name: korepetytio
    environment:
      POSTGRES_DB: korepetytio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - /path/to/store/data:/var/lib/postgresql/data
